/*umer testing merging with branch*/
int x[9];
int func(void){
    return 9;
}

void funcVoid(void){
    return; 
}

void main(void){
    int hello;
    int num[3];

    hello = func();
    num[3] = x[num[3]];
    num[3] = 2;
    hello = x[func()];
    hello = hello = x[3] = 3<2;
    hello = funcVoid();
    hello = x;
    x[2] = num = x;
    
   
}
/* make sure void x; gives error */